source 'https://github.com/CocoaPods/Specs.git'
source 'git@coding.jiamiantech.com:ce/LRSDevRepo/LRSRepos.git'
use_frameworks! :linkage => :static

platform :ios, '11.0'

target 'LRSGlobalDialog_Example' do
  pod 'LRSGlobalDialog', :path => '../'
end
